# Generated by Django 5.2.7 on 2025-10-29 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('specialty', models.CharField(max_length=255)),
                ('years_of_practice', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=255)),
                ('city_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('disease_name', models.TextField()),
                ('conditions_treated', models.TextField(help_text='Enter conditions separated by commas')),
                ('biochemistry_data', models.TextField()),
                ('medical_investigation', models.TextField()),
                ('improvements_observed', models.TextField()),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='patients/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='patients/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='docform.doctor')),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='docform.patient')),
            ],
            options={
                'db_table': 'patient_updates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
